name: Auto Release

on:
  push:
    branches:
      - pre-release
      - main
      # https://docs.github.com/ja/actions/reference/workflows-and-actions/workflow-syntax#filter-pattern-cheat-sheet
      - 'test/**'

jobs:
  release:
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    permissions:
      # タグ作成に書き込み権限が必要
      contents: write
      # リリースノート作成やIssueへのリンクに必要
      issues: write
      # PR へのコメントに必要
      pull-requests: write
    env:
      # `semantic-release` 用の package.json ファイルがあるディレクトリ
      # hashFiles 関数 (https://docs.github.com/ja/actions/reference/evaluate-expressions-in-workflows-and-actions#examples-with-multiple-patterns) でも使うため、
      # `GITHUB_WORKSPACE` からの相対パスで指定
      PROJECT_ROOT: .github

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch all history for all branches and tags
          fetch-depth: 0
          # Partial clone: blobless
          filter: 'blob:none'

      # https://github.com/actions/setup-node
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20

      # https://github.com/actions/cache
      - name: Restore cached node_modules
        id: restore-cache
        uses: actions/cache@v4
        env:
          PACKAGE_JSON: ${{ env.PROJECT_ROOT }}/package.json
        with:
          path: ${{ env.PROJECT_ROOT }}/node_modules
          key: ${{ runner.os }}-semantic-release-${{ hashFiles(env.PACKAGE_JSON) }}

      # https://github.com/semantic-release/semantic-release/blob/master/docs/usage/installation.md#installation
      - name: Install semantic-release
        if: ${{ steps.restore-cache.outputs.cache-hit != 'true' }}
        env:
          # `semantic-release` 本体
          SEMANTIC_RELEASE: 'semantic-release@"^24.2.7"'
          # Conventional Commits 仕様に準拠させる場合に必要なパッケージ
          # https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-conventionalcommits
          CONVENTIONAL_COMMITS: 'conventional-changelog-conventionalcommits@"^9.1.0"'
        # yarn --cwd : https://classic.yarnpkg.com/lang/en/docs/cli/#toc-cwd
        run: |
          yarn --cwd ${{ env.PROJECT_ROOT }} install

      - name: Setup release config
        env:
          SRC_CONFIG: ${{ github.workspace }}/.github/.releaserc.yaml
          LINK: .releaserc.yaml
        run: |
          ln -s  "${SRC_CONFIG}" "${LINK}"
          ls -Alh "${LINK}"

      # リリース処理
      - name: Release
        id: release
        if: ${{ ! startsWith(github.ref_name, 'test/') }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn --cwd ${{ env.PROJECT_ROOT }} semantic-release

      # リリースのテスト用
      - name: Test Release
        if: ${{ steps.release.conclusion == 'skipped' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn --cwd ${{ env.PROJECT_ROOT }} semantic-release --dry-run

